kind: pipeline
name: deploiement application

steps:
  - name: install
    image: node/node:16.13.2
    user: root
    environment:
      GITHUB_APP_URL:
        from_secret: github_app_url
    commands:
      - npm install
      - npm install @angular/cli
      - ng build

  - name: publish  
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      ssh_key:
        from_secret: github_password    
      pages_directory: dist/frontend-mineralcontest
    when:
      branch: main